# Generated by Django 5.0.3 on 2024-05-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.CharField(blank=True, max_length=500, null=True)),
                ('agent', models.CharField(blank=True, max_length=500, null=True)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
